# site settings

title: NGUYEN Phuc Viet Khoa
description: Jekyll theme for a beautiful online CV
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://nguyenphucvietkhoa.github.io/
baseurl: ""
permalink: /:title/
repo: https://github.com/NguyenPhucVietKhoa/NguyenPhucVietKhoa.github.io

# author settings

author:
  name: NGUYEN Phuc Viet Khoa
  email: ng.phucvietkhoa@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: https://github.com/NguyenPhucVietKhoa
  linkedin: https://www.linkedin.com/in/pvknguyen/

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
